# Generated by Django 3.2.9 on 2021-11-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='corona19_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalcases', models.CharField(max_length=200)),
                ('totaldeaths', models.CharField(max_length=200)),
                ('totalrecovered', models.CharField(max_length=200)),
            ],
        ),
    ]
